disabled_rules:
  - redundant_type_annotation
  - redundant_string_enum_value
  - switch_case_alignment

opt_in_rules:
  - empty_count
  - contains_over_filter_count
  - empty_string
  - sorted_imports
  - prefer_key_path

# Customize the severity levels
severity:
  cyclomatic_complexity: error
  function_body_length: warning
  function_parameter_count: warning
  type_body_length: warning
  vertical_parameter_alignment_on_call: warning

# Excluded files and directories
excluded:
  - Carthage
  - Pods
  - fastlane
  - build
  - .build
  - Tests

# Included files and directories
included:
  - Sources
  - Tests

line_length:
  warning: 120
  error: 150

file_length:
  warning: 400
  error: 500

type_name:
  min_length: 3
  max_length: 40
  excluded: i|e|f|x

identifier_name:
  min_length: 2
  max_length: 40
  excluded: id|to|do|in|on|at|up|ok|no|tv|ip|os

function_body_length:
  warning: 50
  error: 100
  ignores_comments: true

type_body_length:
  warning: 200
  error: 350

# Customize the settings for specific rules
trailing_newline:
  ignores_empty_lines: true

# Allow certain rules to be configured
number_separator:
  minimum_length: 5
  exclude_ranges:
    - 1...10